name: khatam_quran
description: 30 Days Khatam Quran

version: 1.0.0+8

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #    quran depedency
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino  s font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^3.0.3289
  scoped_model: ^1.0.1
  font_awesome_flutter: ^8.2.0
  xml2json: ^3.0.3
  queries: ^0.1.4
  bubble_tab_indicator: "^0.1.4"
  sqflite: ^1.0.0
  shimmer: ^1.0.0
  after_layout: ^1.0.7
  shared_preferences: ^0.4.3
  draggable_scrollbar: ^0.0.4
  path: ^1.6.2
  tuple: ^1.0.2
  event_bus: ^1.0.1
  flutter_picker: ^1.0.6
  loadmore: ^1.0.2
  flutter_slidable: ^0.4.9
  sticky_headers: ^0.1.7
  flutter_list_drag_and_drop: ^0.1.6
  dio: ^1.0.13
  encrypt: ^2.0.0
  path_provider: ^0.4.1
  uuid: ^1.0.3
  kiwi: ^0.1.0
  provider: ^1.6.1
  pub_semver: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_analytics: ^2.0.3
  firebase_auth: ^0.8.2
  firebase_messaging: ^4.0.0+4
  cloud_firestore: ^0.9.7

  font_awesome_flutter: ^8.0.1

  flutter_colorpicker: ^0.2.2
  flutter_slidable: ^0.4.9

  url_launcher: ^5.0.2
  share: ^0.6.0+1
  launch_review: ^2.0.0

  modal_progress_hud: ^0.1.3

  connectivity: ^0.4.2

  intl_translation: ^0.17.1
  intl: ^0.15.7
  flutter_launcher_icons: ^0.7.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
  - assets/quran-data/chapters/chapters.en.json
  - assets/quran-data/chapters/chapters.id.json
  - assets/quran-data/juz.json
  - assets/quran-data/translations/id.indonesian.db
  - assets/quran-data/translations/en.sahih.db
  - assets/quran-data/quran-uthmani.db
  - assets/quran-data/translations.db
  - assets/images/
  - assets/appicon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: noorehira
    fonts:
      - asset: fonts/UthmanTN1-Ver10.otf
  - family: KFGQPC Uthman Taha Naskh
    fonts:
      - asset: fonts/UthmanTN1-Ver10.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon/app_icon.png"